sudo: required

addons:
  ssh_known_hosts: 188.166.116.10
  apt:
    packages:
      - sshpass

language: python
python:
  - 3.6

services:
  - docker

before_install:
  - echo 'DOCKER_OPTS="$DOCKER_OPTS --registry-mirror=https://mirror.gcr.io"'
  - sudo service docker restart
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

install:
  - pip install coverage
  - pip install Flask
  - pip install SQLAlchemy
  - pip install psycopg2
  - pip install pylint


before_script:
  - docker-compose build --build-arg POSTGRES_PASSWORD="$POSTGRES_PASSWORD"
  - docker-compose up -d

script:
  - sleep 10
  - cd app && coverage run -m unittest discover -v && cd ..
  - docker-compose push
  - sshpass -p "$SERVICE_PASSWORD" scp docker-compose.yml $SERVICE_LOGIN@$SERVICE_HOST:/root/
  - sshpass -p "$SERVICE_PASSWORD" ssh $SERVICE_LOGIN@$SERVICE_HOST docker-compose pull
  - sshpass -p "$SERVICE_PASSWORD" ssh $SERVICE_LOGIN@$SERVICE_HOST docker-compose up -d 

after_script:
  - docker-compose down
  - bash <(curl -s https://codecov.io/bash)
  - cd app && pylint lms || exit 0

