sudo: required

services:
  - docker

before_script:
  - docker-compose up -d --build

script:
  - docker-compose exec python -m unittest tests/controllers_test.py

after_script:
  - docker-compose down

