sudo: required

services:
  - docker

before_install:
  - echo 'DOCKER_OPTS="$DOCKER_OPTS --registry-mirror=https://mirror.gcr.io"'
  - sudo service docker restart

before_script:
  - docker-compose up -d --build

script:
  - docker-compose exec app python -m unittest tests/controllers_test.py

after_script:
  - docker-compose down

