sudo: required

addons:
  ssh_known_hosts: $SERVICE_HOST
  apt:
    packages:
      - sshpass

language: python
python:
  - 3.6

services:
  - docker

before_install:
  - echo 'DOCKER_OPTS="$DOCKER_OPTS --registry-mirror=https://mirror.gcr.io"'
  - sudo service docker restart
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

install:
  - pip install coverage
  - pip install Flask
  - pip install SQLAlchemy
  - pip install psycopg2
  - pip install pylint


before_script:
  - docker-compose up -d --build

script:
  - sleep 10
  - cd app && coverage run -m unittest discover -v
  - sshpass -p "$SERVICE_PASSWORD" scp docker-compose.yml $SERVICE_LOGIN@$SERVICE_HOST:/root/LMS/
  - sshpass -p "$SERVICE_PASSWORD" ssh $SERVICE_LOGIN@$SERVICE_HOST cd LMS && docker-compose pull && docker-compose up -d 
  - pylint lms || 0

after_script:
  - docker-compose down
  - bash <(curl -s https://codecov.io/bash)

