version: "3"
services:
  db_service:
    build: 
      context: postgres/
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"
    container_name: lms-postgres
  # rest:
  #   build: 
  #     context: rest/
  #   depends_on:
  #     - dbcreater_service
  #   environment:
  #     POSTGRES_PASSWORD: example
  #   ports:
  #     - "5000:5000"
  #   network_mode: host
